### PR TITLE
add support to spa

### PR DESCRIPTION
**Pull request by thiagones**
# Pull Request Details

## Related Issue
Please, open an issue before a pull request. It will help in understanding better the PR aim.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation or my changes dont require it.
- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes (or the existing one were enough).
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by daquinoaldo** [comment]
Hi @thiagones, thank you for your interest!

I think this already implemented at [line 65](https://github.com/daquinoaldo/https-localhost/blob/39a825aae21393423ad156e83a1243453d571ee0/index.js#L65). Maybe you would like to improve this functionality?

From a first look you are also adding the CLI option --spa. I found it useful. There is a scheduled v5.0 (as soon as I have the time) in which I want to improve the CLI.
Would you like to discuss some possible option and try to submit a draft for the CLI to be used as skeleton of the next version?

Aside from that, there is a CI on this repo, PR will be approved only when it pass all tests.

**Comment by daquinoaldo** [comment]
@thiagones are you still interested in contributing to this project?

**Comment by gstvribs** [comment]
Hi, @daquinoaldo i could work on this PR, there are any plans to support spa application in https-localhost?
(i think that could be a option on CLI) like a flag `--spa` when running the command.

The serve from zeit uses `-s` flag.

**Comment by daquinoaldo** [comment]
Hi, it should be spa by default, isn't it? How would you like to implement this flag? I'm open to proposals.

**Pull request closed without merging**
