### PR TITLE
Accessing static files on server without using express module.

### PR DESCRIPTION
**Pull request by HeyIts-RJ**
#29  Pull Request Details

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [X] I have updated the documentation or my changes dont require it.
- [X] I have read the [CONTRIBUTING](CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes (or the existing one were enough).
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by daquinoaldo** [comment]
I've fixed tests.
Actually, your implementation doesn't serve files... have you tested it?
I've prepared you a skeleton with some comments. The problems are:
- missing headers
- in my skeleton the file is sent, which means the file will be downloaded. Instead, it must be streamed
- the 404 page doesn't work (but it's not the main problem right now)

You can check the script behavior with `[sudo] npm start test`. Sudo may be required on Linux.

**Comment by HeyIts-RJ** [comment]
When I run tests on the following the lines
```

fs.readFile(staticPath + "/" + req.url, function(err, data) {
        if (err) {
        } else {
          // redirect 404 to 404.html or to index.html
          if (!staticPath.startsWith("/"))
            staticPath = process.cwd() + "/" + staticPath
          const p404 = staticPath + "/404.html"
          const index = staticPath + "/index.html"
          // istanbul ignore else: not interesting
          if (fs.existsSync(p404))
            res.status(404).sendFile(p404)
          else if (fs.existsSync(index))
            res.status(404).sendFile(index)
          else res.status(404).send(req.path + " not found.")
        } // else { // no error, serve the file
        /* TODO: set the headers. Some examples:
            - Content-Length
            - Content-Type
            - Content-Encoding
            - Expires
            - Last-Modified
          */
        // TODO: the data must be streamed
        // res.status(200).send(data)
        // }
      })
```

I get these test errors

>   Testing serve
Serving static path: test
Server running on port 4443.
(node:20392) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(res.data.toString() ===
  fs.readFileSync("test/static.html").toString())

    at makeRequest.then.res (d:\hacktober\https-localhost\test\test.js:182:22)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:20392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    1) serves static files from custom path
Serving static path: test
Server running on port 4443.
(node:20392) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(res.data.toString() ===
  fs.readFileSync("test/static.html").toString())

    at makeRequest.then.res (d:\hacktober\https-localhost\test\test.js:196:22)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:20392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
    2) serves static files from default env port
Serving static path: d:\hacktober\https-localhost
Server running on port 4443.
    3) doesn't crash on 404
Serving static path: test
Server running on port 4443.
    4) looks for a 404.html file
Serving static path: does-not-exist
Server running on port 4443.
    5) doesn't crash if the static path doesn't exists

  Testing redirect
http to https redirection active.
    √ redirect http to https
http to https redirection active.
    √ redirect http to https with custom ports
http to https redirection active.
    √ redirect http to https with env port

  Testing additional features
Serving static path: test
    √ is ready for production (2930ms)
Server running on port 4443.


  13 passing (1m)
  5 failing

  1) Testing serve
       serves static files from custom path:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (d:\hacktober\https-localhost\test\test.js)
  

  2) Testing serve
       serves static files from default env port:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (d:\hacktober\https-localhost\test\test.js)
  

  3) Testing serve
       doesn't crash on 404:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (d:\hacktober\https-localhost\test\test.js)
  

  4) Testing serve
       looks for a 404.html file:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (d:\hacktober\https-localhost\test\test.js)
  

  5) Testing serve
       doesn't crash if the static path doesn't exists:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (d:\hacktober\https-localhost\test\test.js)

**Comment by daquinoaldo** [comment]
```
if (err) {
} else {
// redirect 404 to 404.html or to index.html
...
} else {
serve files
}
```

Actually, the second part, all the code inside the first `else` (`// redirect 404...`), should be inside the `if(err)`.
That is:
```
fs.readFile(staticPath + "/" + req.url, function(err, data) {
        if (err) { // ERROR WHEN YOU READ THE FILE, SEND 404.html, or index.html, or "path not found"
          // redirect 404 to 404.html or to index.html
          if (!staticPath.startsWith("/"))
            staticPath = process.cwd() + "/" + staticPath
          const p404 = staticPath + "/404.html"
          const index = staticPath + "/index.html"
          // istanbul ignore else: not interesting
          if (fs.existsSync(p404))
            res.status(404).sendFile(p404)
          else if (fs.existsSync(index))
            res.status(404).sendFile(index)
          else res.status(404).send(req.path + " not found.")
        } // else { // NO ERRORS, FILE FOUND, SEND THE FILE CONTENT
        /* TODO: set the headers. Some examples:
            - Content-Length
            - Content-Type
            - Content-Encoding
            - Expires
            - Last-Modified
          */
        // TODO: the data must be streamed
        // res.status(200).send(data)
        // }
      })
```

**Comment by HeyIts-RJ** [comment]
@daquinoaldo can you please check my code in the last commit. I added all the headers but failing the tests.

```
          res.setHeader("content-length", Buffer.byteLength(data, "utf-8"))
          res.setHeader("content-type", "text/html")
          res.setHeader("Cache-Control", "public, max-age=345600") // 4 days
          res.setHeader("Expires", new Date(Date.now() + 3456000).toUTCString())
          res.setHeader("Last-Modified", new Date())
          // TODO: the data must be streamed
          res.pipe(data)
          res.status(200)
```

**Comment by daquinoaldo** [comment]
```
Error [ERR_STREAM_CANNOT_PIPE]: Cannot pipe, not readable
```

I suppose the error is in that `res.pipe(data)`.

**Comment by HeyIts-RJ** [comment]
> ```
> Error [ERR_STREAM_CANNOT_PIPE]: Cannot pipe, not readable
> ```
> 
> I suppose the error is in that `res.pipe(data)`.

So think we just simply use `res.send(data)`

**Comment by daquinoaldo** [comment]
> So think we just simply use `res.send(data)`

Have you tried the result?
The aim of this tool is to let developers test a static website on localhost, so we need to let them _view_ the page, not _download_ it.

Remember to test your code both automatically with `npm t` and manually with `npm start test` and then check the result on https://localhost.

**Comment by HeyIts-RJ** [comment]
Alright, @daquinoaldo so the problem is that file is getting downloaded rather than displaying in the browser.

**Comment by HeyIts-RJ** [comment]
@daquinoaldo stream problem can be solved by sending `data.toString()` in response.

**Comment by daquinoaldo** [comment]
@HeyIts-RJ please try to implement this in the code and run the test to check if it works, and then commit it if you succeed.

**Comment by HeyIts-RJ** [comment]
> @HeyIts-RJ please try to implement this in the code and run the test to check if it works, and then commit it if you succeed.

All testing is passed only getting this error in npm start test
```
1) Testing serve
       looks for a 404.html file:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (d:\hacktober\https-localhost\test\test.js)
```

**Comment by daquinoaldo** [comment]
There is a problem with serving the 404.html file. Try `node index.js test` and go to https://localhost/404.htm. You should see [this file](https://github.com/daquinoaldo/https-localhost/blob/master/test/404.html). You probably won't, since you get the error in the automated test. You can edit the 404.html file to check if it is really that one.

**Comment by HeyIts-RJ** [comment]
> There is a problem with serving the 404.html file. Try `node index.js test` and go to https://localhost/404.htm. You should see [this file](https://github.com/daquinoaldo/https-localhost/blob/master/test/404.html). You probably won't, since you get the error in the automated test. You can edit the 404.html file to check if it is really that one.

Yes it is working i can see File Not Found. in body

**Comment by daquinoaldo** [comment]
Fine, thank you very much!
Seems work 🙌
Next week I'll perform some manual tests and if everything is okay I'll merge the PR into a new branch for v5.0.0.

**Comment by HeyIts-RJ** [comment]
Sounds good! 😀😀

**Comment by daquinoaldo** [comment]
@HeyIts-RJ Bad news, it still not working.
Have you tried to do as I suggested?

```
node index.js test
```
And then visit https://localhost/static.html

Please, require another review only if:
- [ ] `npm test` doesn't report any error
- [ ] https://localhost/static.html shows the files, without asking you to download it
- [ ] After the commit the CI doesn't report any error

**Pull request closed without merging**
