### PR TITLE
change exports to a factory

### PR DESCRIPTION
**Pull request by stutrek**
# PR Details

This makes the exports of the module a factory function rather than exporting app directly. Doing this brings the API in line with express and allows you to create more than one app in a node process.

This is a breaking change, but could be converted to a non-breaking change by continuing to export the app and adding the factory function to it. I decided against that because I thought people would expect it to work like express.

## Motivation and Context

I maintain a development server that allows you to start multiple http servers with webpack-dev-middleware using a single command. The use cases are:

- If you're creating two versions of an app (maybe a lite and a pro, or for two different user types) this allows you to run both.
- You can run things like storybook or other testing environments.
- You can run multiple back end process simultaneously.

## How Has This Been Tested

Unit tests pass. I am using it locally in my dev server.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) document. (does not exist)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by daquinoaldo** [comment]
Thank you for your work!
I'll review your PR as soon as I can!

**Comment by daquinoaldo** [comment]
Merged!
Thank you for your contribution and for all the details that you provide.

**Comment by daquinoaldo** [comment]
Published on npm with tag `v4.0.0`.

**Comment by stutrek** [comment]
Thanks!

I was thinking about this last night, I will want it to ask for a password (if required) when you first _run_ the server, rather than when it's installed. If you're open I'll try to make that change next weekend.

**Comment by daquinoaldo** [comment]
The password is the sudo password I suppose.
It is needed to generate the certificates, so you are proposing to generate certificates at first run?

**Comment by stutrek** [comment]
Yes, exactly. With a message "Please enter your password to enable https" or something similar.

**Comment by daquinoaldo** [comment]
Make sense. Can you implement that?

I also open an issue #8 that I would like to implement sooner or later. If it you would like to take a look, I think it could be easier to implement with your proposal edits, otherwise I'll implement myself when I have time.

**Pull request merged**
